apiVersion: v1
kind: Service
metadata:
  name: {{ include "dinner-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "dinner-app.name" . }}
  ports:
    - port: 8888
      targetPort: 8888
